# Course Name: Visualisation for Data Analytics
# Objective: Data Pre-Processing

### Dataset credit: https://archive.ics.uci.edu/ml/datasets/Breast+Cancer 
#### NOTE: I have modified some parts of the dataset and added missng values in it

In [1]:
# Import Libraries
import numpy as np
import pandas as pd 

from pandas import Series, DataFrame

# Read Data given to in csv file with the lab

In [2]:
data = pd.read_csv('breast-cancer.csv')
#print(data.head())
data

class    age menopause tumor-size inv-nodes node-caps  \
0    no-recurrence-events  30-39   premeno      30-34       0-2       NaN   
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  40-49   premeno      20-24       0-2        no   
3    no-recurrence-events  60-69      ge40      15-19       0-2        na   
4    no-recurrence-events  40-49   premeno        0-4       0-2             
..                    ...    ...       ...        ...       ...       ...   
281     recurrence-events  30-39   premeno      30-34       0-2        no   
282     recurrence-events  30-39   premeno      20-24       0-2        no   
283     recurrence-events  60-69      ge40      20-24       0-2        no   
284     recurrence-events  40-49      ge40      30-34     5-Mar        no   
285     recurrence-events  50-59      ge40      30-34     5-Mar        no   

     deg breast breast-quad irradiat  
0    NaN   left    left_low       no  
1    2.0  right    right_up       no  
2    2.0  right    right_up       no  
3    NaN  right     left_up       no  
4    2.0  right   right_low       no  
..   ...    ...         ...      ...  
281  2.0   left     left_up       no  
282  3.0   left     left_up      yes  
283  1.0  right     left_up       no  
284  3.0   left    left_low       no  
285  3.0   left    left_low       no  

[286 rows x 10 columns]

In [3]:
data.isnull().sum()
#Find the null value count of the attributes/colum header/features

class          0
age            0
menopause      0
tumor-size     0
inv-nodes      2
node-caps      3
deg            3
breast         0
breast-quad    0
irradiat       0
dtype: int64

### Q1. find null values for the column 'deg'

In [4]:
print(data['deg'].isnull())


0       True
1      False
2      False
3       True
4      False
       ...  
281    False
282    False
283    False
284    False
285    False
Name: deg, Length: 286, dtype: bool


### Q2 Find null values for the column 'node-cap'

In [5]:
print(data['node-caps'].isnull())


0       True
1      False
2      False
3      False
4      False
       ...  
281    False
282    False
283    False
284    False
285    False
Name: node-caps, Length: 286, dtype: bool


In [6]:
# we have to define the null values as a list and pass it as an input while reading the data
missing_values = ["n/a", "na", "--", ' ', '?', 'NaN']
data = pd.read_csv('breast-cancer.csv', na_values = missing_values)
print(data['node-caps'].isnull())

0       True
1      False
2      False
3       True
4       True
       ...  
281    False
282    False
283    False
284    False
285    False
Name: node-caps, Length: 286, dtype: bool


### Q3. Count the percenatge of missing values in column 'deg'. Drop this columns if the percentage of missing values in greater than equal to 75%. 

In [7]:
missing_val_count = data['deg'].isnull().sum()
print('Number of missing values = ', missing_val_count)
rows = data['deg'].count()
print('count =', rows)
percentage_missing  =  (missing_val_count *100)/rows
print('Percentage missing = ', percentage_missing)
if percentage_missing >=75.0:
    print('Delete this coulmn')
    data.drop('deg', axis= 1,inplace = True)
    
print(data)

Number of missing values =  3
count = 283
Percentage missing =  1.0600706713780919
                    class    age menopause tumor-size inv-nodes node-caps  \
0    no-recurrence-events  30-39   premeno      30-34       0-2       NaN   
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  40-49   premeno      20-24       0-2        no   
3    no-recurrence-events  60-69      ge40      15-19       0-2       NaN   
4    no-recurrence-events  40-49   premeno        0-4       0-2       NaN   
..                    ...    ...       ...        ...       ...       ...   
281     recurrence-events  30-39   premeno      30-34       0-2        no   
282     recurrence-events  30-39   premeno      20-24       0-2        no   
283     recurrence-events  60-69      ge40      20-24       0-2        no   
284     recurrence-events  40-49      ge40      30-34     5-Mar        no   
285     recurrence-events  50-59      ge40      30-34     5-Mar       

### Q4. Replace the 'null' values by average for the 'deg' column?

In [8]:
mean = data['deg'].mean()
print('mean value=', mean)
print('Befor:\n ', data['deg'])
data['deg'].fillna(mean, inplace=True)
print('after:\n',data['deg'])


mean value= 2.0424028268551235
Befor:
  0      NaN
1      2.0
2      2.0
3      NaN
4      2.0
      ... 
281    2.0
282    3.0
283    1.0
284    3.0
285    3.0
Name: deg, Length: 286, dtype: float64
after:
 0      2.042403
1      2.000000
2      2.000000
3      2.042403
4      2.000000
         ...   
281    2.000000
282    3.000000
283    1.000000
284    3.000000
285    3.000000
Name: deg, Length: 286, dtype: float64


### Q5. Drop rows consisting of null or missing values 

In [9]:
print('print data before and after dropping rows consisting of missing values')
data

print data before and after dropping rows consisting of missing values


class    age menopause tumor-size inv-nodes node-caps  \
0    no-recurrence-events  30-39   premeno      30-34       0-2       NaN   
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  40-49   premeno      20-24       0-2        no   
3    no-recurrence-events  60-69      ge40      15-19       0-2       NaN   
4    no-recurrence-events  40-49   premeno        0-4       0-2       NaN   
..                    ...    ...       ...        ...       ...       ...   
281     recurrence-events  30-39   premeno      30-34       0-2        no   
282     recurrence-events  30-39   premeno      20-24       0-2        no   
283     recurrence-events  60-69      ge40      20-24       0-2        no   
284     recurrence-events  40-49      ge40      30-34     5-Mar        no   
285     recurrence-events  50-59      ge40      30-34     5-Mar        no   

          deg breast breast-quad irradiat  
0    2.042403   left    left_low       no  
1    2.000000  right    right_up       no  
2    2.000000  right    right_up       no  
3    2.042403  right     left_up       no  
4    2.000000  right   right_low       no  
..        ...    ...         ...      ...  
281  2.000000   left     left_up       no  
282  3.000000   left     left_up      yes  
283  1.000000  right     left_up       no  
284  3.000000   left    left_low       no  
285  3.000000   left    left_low       no  

[286 rows x 10 columns]

In [10]:
#Drop rows consisting of null values
data.dropna(inplace=True)
data

class    age menopause tumor-size inv-nodes node-caps  \
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  40-49   premeno      20-24       0-2        no   
5    no-recurrence-events  60-69      ge40      15-19       0-2        no   
6    no-recurrence-events  50-59   premeno      25-29       0-2        no   
9    no-recurrence-events  40-49   premeno      20-24       0-2        no   
..                    ...    ...       ...        ...       ...       ...   
281     recurrence-events  30-39   premeno      30-34       0-2        no   
282     recurrence-events  30-39   premeno      20-24       0-2        no   
283     recurrence-events  60-69      ge40      20-24       0-2        no   
284     recurrence-events  40-49      ge40      30-34     5-Mar        no   
285     recurrence-events  50-59      ge40      30-34     5-Mar        no   

          deg breast breast-quad irradiat  
1    2.000000  right    right_up       no  
2    2.000000  right    right_up       no  
5    2.000000   left    left_low       no  
6    2.000000   left    left_low       no  
9    2.042403  right     left_up       no  
..        ...    ...         ...      ...  
281  2.000000   left     left_up       no  
282  3.000000   left     left_up      yes  
283  1.000000  right     left_up       no  
284  3.000000   left    left_low       no  
285  3.000000   left    left_low       no  

[270 rows x 10 columns]

In [11]:
#Check for finding null values in the df
data.isnull().sum()


class          0
age            0
menopause      0
tumor-size     0
inv-nodes      0
node-caps      0
deg            0
breast         0
breast-quad    0
irradiat       0
dtype: int64

### Q6. Find and drop rows consisting of duplicate data? 

In [12]:
#Finding duplicated data
data.duplicated()

1      False
2       True
5      False
6      False
9      False
       ...  
281    False
282    False
283    False
284    False
285    False
Length: 270, dtype: bool

In [13]:
# To drop all duplicate rows, just call the drop_duplicates() method off of the DataFrame.
data.drop_duplicates(inplace =True)

In [14]:
data.duplicated()


1      False
5      False
6      False
9      False
10     False
       ...  
281    False
282    False
283    False
284    False
285    False
Length: 257, dtype: bool

### Q7 Encode  columns consisting of categorical data using 'OrdinalEncoder'

In [15]:
from sklearn import preprocessing
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

# ordinal encode input variables
ordinal = OrdinalEncoder()
print(data)

                    class    age menopause tumor-size inv-nodes node-caps  \
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
5    no-recurrence-events  60-69      ge40      15-19       0-2        no   
6    no-recurrence-events  50-59   premeno      25-29       0-2        no   
9    no-recurrence-events  40-49   premeno      20-24       0-2        no   
10   no-recurrence-events  40-49   premeno        0-4       0-2        no   
..                    ...    ...       ...        ...       ...       ...   
281     recurrence-events  30-39   premeno      30-34       0-2        no   
282     recurrence-events  30-39   premeno      20-24       0-2        no   
283     recurrence-events  60-69      ge40      20-24       0-2        no   
284     recurrence-events  40-49      ge40      30-34     5-Mar        no   
285     recurrence-events  50-59      ge40      30-34     5-Mar        no   

          deg breast breast-quad irradiat  
1    2.000000  right    right_u

In [16]:
data = ordinal.fit_transform(data)
print('Encode Data')
print(data) 

Encode Data
[[0. 2. 2. ... 1. 4. 0.]
 [0. 4. 0. ... 0. 1. 0.]
 [0. 3. 2. ... 0. 1. 0.]
 ...
 [1. 4. 0. ... 1. 2. 0.]
 [1. 2. 0. ... 0. 1. 0.]
 [1. 3. 0. ... 0. 1. 0.]]


More info

https://machinelearningmastery.com/one-hot-encoding-for-categorical-data/#:~:text=This%20OrdinalEncoder%20class%20is%20intended,LabelEncoder%20class%20can%20be%20used.

